# Generated by Django 4.0.3 on 2022-08-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_glb',
            field=models.ImageField(blank=True, null=True, upload_to='product_glb/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usdz',
            field=models.ImageField(blank=True, null=True, upload_to='product_usdz/'),
        ),
    ]
