# Generated by Django 4.0.3 on 2022-08-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_product_glb_product_product_usdz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_glb',
            field=models.FileField(blank=True, null=True, upload_to='product_glb/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usdz',
            field=models.FileField(blank=True, null=True, upload_to='product_usdz/'),
        ),
    ]
